# Generated by Django 4.1 on 2024-03-05 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('track_score', models.FloatField()),
                ('album_cover', models.URLField(max_length=1024)),
                ('number_of_tracks', models.IntegerField()),
                ('horrible_ratio', models.FloatField()),
                ('bad_ratio', models.FloatField()),
                ('ok_ratio', models.FloatField()),
                ('like_ratio', models.FloatField()),
                ('love_ratio', models.FloatField()),
                ('favs_ratio', models.FloatField()),
                ('gut_feeling', models.FloatField()),
                ('calculated_score', models.FloatField()),
                ('unified_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='albums.album')),
            ],
        ),
    ]
